### ISSUE TITLE
CCURL Paper

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#103]
I am going to submit a paper to [CCURL](http://www.ilc.cnr.it/ccurl2016/) in the next week. In this thread, I'll post updates and notes that I need to take that I think might as well be public. 

- [ ] Take a look at the ISO 639 Meeting notes from ELP
- [ ] Talk to ELP about being involved
- [ ] Take a look at LSA notes
- [ ] Write up LSA notes
- [ ] Reference the Ethnologue issues

**Comment by HughP** [comment]
_What do you mean by ELP? _

_What do you mean by Ethnologue issues?_
Some people talk like they have problems with the "ethnologue" but really they should be talking about the ISO 639-3.... the real problem is that they have conflated the two items.  A good recap is the following: https://tke2014.coreon.com/slides/2014_06_21_104_1030_Simons.pdf 

You might have a look at this blog post and my comments there: http://dlc.hypotheses.org/610 Not sure if that is the direction of your current interest, but it might give you some background. If it is not the direction of your current interest, please elaborate.

This line of thinking my benefit from a skype call. PM me.

**Comment by RichardLitt** [comment]
Submitted.
