### ISSUE TITLE
LSA CELP Technology Subcommittee

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#106]
I am trying to head up an LSA subcomittee for technology within the Committee for Endangered Language Preservation. I've written this to Shobhana, the current chair, and she says she's passed it on to the LSA EC. 

> I was thinking that it would be smart to have some members who are interested in the technical side of documenting, preserving, and revitalizing endangered languages. Without have tools or translations for internet services available, most languages cannot survive on the web, which affects their growth and health. Also, for researchers, it would be good if there was an place they could ask technical questions: what apps are best to use to help various communities, how to best archive data, what healthy tech usage would look like. 
> 
> I imagine a technical committee could provide this. It would exist to help with queries regarding technology useful for endangered language communities, to provide advice on tech relevant to research, to liaise with computational linguists and developers who need theoretical input for low resource languages, to promote tech aimed at endangered languages, and to deal with policies and issues that arise that have technical concerns (such as Ethnologue). 
> 
> I don't think this is related to the Media committee, which has as it's core promotion. It doesn't tackle any issues, like the Ethnologue debacle, which may arise.  There might be a case for not having a Tech committee in the LSA, at all. Most researchers working on this issue are not likely to be in the LSA, but rather in ACL. I think it's a net loss if we don't have a bridge between the two communities, however. This could be something like that. 

Posting this here in case anyone here is interested in helping out, is in the LSA and has feedback, is in ACL, and to generally gather support.

**Comment by AnnaLuisaD** [comment]
Hi Richard,

I agree there should be more of a bridge between the ACL and the LSA. I
would be interested in being on the technical committee if one is formed.
While I am fairly new to programming, I have been documenting endangered
languages since 2008, and have participated in the creation of over 40
Talking Dictionaries for minority languages throughout the Americas and in
the Pacific region. I am working on increasing my knowledge about
programming and data analytics so I can be more systematic about the way I
work and how I present my data.

I have observed that endangered language communities need technical
assistance with a huge range of topics, ranging from basic computer
literacy, to software training, to the ability to use special characters to
communicate on the web and on mobiles devices, and have translation
services available. Also, field linguists who work with speakers of
endangered languages often need a lot of technical assistance and expertise
when it comes to organizing and cataloging information and being systematic
about archiving and creating access to their recorded materials.

It would be good to get the opinion of someone like Harald Hammarstrom who
has done amazing work that balances computational linguistics and
endangered language research, creating sites such as Glottolog, SAILS, and
others.

keep me in the loop,
Anna Luisa
annaluisa@livingtongues.org



*Anna Luisa Daigneault, M.Sc*
Development Officer & Latin America Projects Coordinator
Living Tongues Institute for Endangered Languages

Website <http://livingtongues.org/> | Facebook
<https://www.facebook.com/living.tongues/>| Twitter
<https://twitter.com/livingtongues> | Youtube
<https://www.youtube.com/user/EnduringVoices>

Archivo digital de la memoria yanesha
Arr añño'tena poeñotenaxhno yanesha
www.yanesha.com

**Comment by RichardLitt** [comment]
Thanks @AnnaLuisaD! Agreed that this would be useful, and that there's a need for better computational literacy around these topics. I'll see how far we get before contacting people directly, but Hammarstrom would be a good person to have on board // to ask for advice from. I'll keep you updated.

**Comment by HughP** [comment]
+1 for being on the committee. But I suspect that you would have anticipated that.

**Comment by RichardLitt** [comment]
Followed up again. Let's see if we can get this rolling.

**Comment by RichardLitt** [comment]
Going to work on this off-band. This issue is not relevant to this repository.
