### ISSUE TITLE
Add SIL resources

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/endangered-languages#29]
https://github.com/silnrsi

**Comment by HughP** [comment]
There are two other SIL accounts, one is LSDev and one is SILInternational

**Comment by RichardLitt** [comment]
Thanks. Will check both of those.

**Comment by RichardLitt** [comment]
https://github.com/sillsdev
https://github.com/silinternational

**Comment by mapmeld** [comment]
Since you are mentioning SIL, please add their Bloom Library https://github.com/BloomBooks/BloomDesktop - this is a .NET application which just won the USAID Enabling Writers competition for writing primary school books in local languages. I was on another finalist team for a Haitian Creole writer, but our project isn't production-ready - would be happy to add when we're ready.

**Comment by RichardLitt** [comment]
Done! Thanks. :)

**Comment by RichardLitt** [comment]
@mapmeld Any news on that other project? :)
