### ISSUE TITLE
Link to `XLTK` broken

### ISSUE THREAD

**Issue by arthurvr** [RichardLitt/endangered-languages#73]
> XLTK eXtensible Language ToolKit

The link on that item seems broken.

**Comment by RichardLitt** [comment]
Thanks @arthurvr. @alvations any idea what happened here?

**Comment by alvations** [comment]
Yes, we've to remove it publically when there was some discussion that someone wanted to buy the tool and the tool was rejected in LREC last year. The deal didn't pull through and the  tool has been in limbo since. I think it's better to remove the link =) Someday, someday I might revive it or as the LREC reviewer said, "this should be part of NLTK".

**Comment by alvations** [comment]
@arthurvr , out of curiosity, do you know what XLTK was doing before it was removed?

**Comment by RichardLitt** [comment]
Thanks Liling! Good to know.

**Comment by arthurvr** [comment]
@alvations I didn't know it that's why I was interested :p

**Comment by alvations** [comment]
;P possibly someday it will reappear as something else.
